### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Level8Broccoli** [Level8Broccoli/tatenen#2]
- [ ] fail2ban (see https://github.com/Level8Broccoli/ansible-setup/tree/main/roles/fail2ban, add at least one IP onto whitelist)
- [x] UFW (https://github.com/Level8Broccoli/ansible-setup/tree/main/roles/firewall)
- [x] UnattendedUpgrades
- [x] Restrict (https://github.com/Level8Broccoli/ansible-setup/tree/main/roles/restrict)
- [ ] Build docker containers regularly from scratch (e.g. once per week)
- [ ] Configure mail for cron jobs
- [ ] Backup solution (DB need to be flushed? Where to back up?)
- [x] Logging solution (https://docs.docker.com/config/containers/logging/syslog/)

Maybe
- [ ] 2FA with https://goteleport.com/

Applications on every server
- [x] Docker + Docker compose
- [x] Prometheus and Grafana
- [ ] Logs in Grafana
- [x] Portainer
